apiVersion: apps/v1
kind: Deployment
metadata:
  name: swe645-deployment
  namespace: swe645-namespace  # Specify the namespace here
spec:
  replicas: 3  # Number of pod replicas
  selector:
    matchLabels:
      app: survey-app
  template:
    metadata:
      labels:
        app: survey-app
    spec:
      containers:
      - name: container-0
        image: abhiram1212/survey645:latest  # Use the latest tag or a specific tag
        ports:
        - containerPort: 8080  # Adjust to match the exposed port of your app
